#!/bin/bash

set -e

echo "Setting up localization."
echo

changed_locale=$(sed 's/#\(en_US.UTF-8 UTF-8\)/\1/' /etc/locale.gen)
echo "$changed_locale" >/etc/locale.gen

echo "LANG=en_US.UTF-8" >/etc/locale.conf

locale-gen
