#!/bin/bash

set -e

echo "Setting up swapfile."
echo

if [[ -f /swapfile ]]; then
  echo "A swapfile already exists, removing."
  swapoff -a
  rm -f /swapfile
fi

total_mem_kib=$(grep MemTotal /proc/meminfo | awk '{print $2}')
swapfile_size=$(( total_mem_kib / 1024 ))

echo "Creating a swapfile of size $swapfile_size at /swapfile."

dd if=/dev/zero of=/swapfile bs=1M count=$swapfile_size status=progress
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile

if ! grep -q /swapfile /etc/fstab; then
  echo "/swapfile	none	swap	defaults	0	0" >>/etc/fstab
fi
