#!/bin/bash

set -e

echo "Setting up swapfile."
echo

if [[ -f /swapfile ]]; then
  echo "A swapfile already exists, removing."
  swapoff -a
  rm -f /swapfile
fi

while true; do
  echo -n "How many MiB should the swapfile be: "
  read swapsize
  echo "Are you sure you want to make a swapfile of size ${swapsize} MiB?"
  select yn in "Yes" "No"; do
    case $yn in
      Yes) breakloop=1; break;;
      No) breakloop=0; break;;
    esac
  done
  if [[ breakloop -eq 1 ]]; then
    break
  fi
done

echo "Creating a $swapsize MiB swapfile at /swapfile."

dd if=/dev/zero of=/swapfile bs=1M count=$swapsize status=progress
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile

if ! grep -q /swapfile /etc/fstab; then
  echo "/swapfile	none	swap	defaults	0	0" >>/etc/fstab
fi
