#!/bin/bash

set -e

echo "Setting up network."
echo

pacman -S iw wpa_supplicant wpa_actiond dialog

wireless_interface=$(find /sys/class/net/ -iname "*wl*" | head -n1)
systemctl enable netctl-auto@"$wireless_interface"

hostname=$(cat /etc/hostname)
echo "127.0.0.1	localhost
::1		localhost
127.0.1.1	$hostname.localdomain	$hostname" >/etc/hosts

changed_default_link=$(sed 's~MACAddressPolicy=.*~MACAddressPolicy=random~' /usr/lib/systemd/network/99-default.link)
echo "$changed_default_link" >/usr/lib/systemd/network/99-default.link

echo
echo "/etc/hosts content set to:"
cat /etc/hosts
