#!/bin/bash

set -e

echo "Setting up network."
echo

pacman -S iwd

systemctl enable systemd-networkd
systemctl enable systemd-resolved

hostname=$(cat /etc/hostname)
echo "127.0.0.1	localhost
::1		localhost
127.0.1.1	$hostname.localdomain	$hostname" >/etc/hosts

sed -i 's~MACAddressPolicy=.*~MACAddressPolicy=random~' /usr/lib/systemd/network/99-default.link

echo "[Match]
Name=w*

[Network]
DHCP=yes" >/etc/systemd/network/25-wireless.network

echo
echo "/etc/hosts content set to:"
cat /etc/hosts
