#!/bin/bash

echo "Creating user."
echo

changed_sudoers=$(cat /etc/sudoers | sed 's/.*\(%wheel ALL=(ALL) ALL\)/\1/')
echo "$changed_sudoers" >/etc/sudoers

if [[ $(getent passwd | grep -c "^$USERNAME:") -eq 1 ]]; then
    echo "User $USERNAME already exists, removing."
    userdel -r -f $USERNAME
fi

useradd -m -s /bin/bash $USERNAME
usermod -a -G wheel,audio,video $USERNAME

echo "Setting up passwords."
echo "Root:"
passwd
echo "$USERNAME:"
passwd $USERNAME

echo "Making home dirs."

cd /home/$USERNAME
sudo -u $USERNAME mkdir -p projects
sudo -u $USERNAME mkdir -p random
sudo -u $USERNAME mkdir -p tools
sudo -u $USERNAME mkdir -p wallpapers
cp $SETUP_DIR/arch.png wallpapers
