#!/bin/bash

set -e

echo "Creating user."
echo

sed -i 's/.*\(%wheel ALL=(ALL) ALL\)/\1/' /etc/sudoers

if [[ $(getent passwd | grep -c "^$USERNAME:") -eq 1 ]]; then
  echo "User $USERNAME already exists, removing."
  userdel -r -f "$USERNAME"
fi

useradd -m -s /bin/bash "$USERNAME"
usermod -a -G wheel,audio,video "$USERNAME"

echo "Setting up passwords."
echo "Root:"
passwd
echo "$USERNAME:"
passwd "$USERNAME"

echo "Making home dirs."

cd /home/"$USERNAME"
sudo -u "$USERNAME" mkdir -p downloads
sudo -u "$USERNAME" mkdir -p projects
sudo -u "$USERNAME" mkdir -p random
sudo -u "$USERNAME" mkdir -p tools

echo "Setting up basic wallpapers."

pacman -S archlinux-wallpaper

sudo -u "$USERNAME" mkdir -p .wallpapers
ln -s /usr/share/backgrounds/archlinux/* .wallpapers