#!/bin/bash

echo "Setting up user packages."
echo

pacman -S qt5-base qt4 vlc pulseaudio gedit gtop htop iotop jdk10-openjdk openjdk10-doc openjdk10-src \
java-openjfx java-openjfx-doc java-openjfx-src gimp cowsay lolcat fortune-mod nmap openssh python python-pip sl keepass \
tree xfce4-terminal shotwell ttf-ubuntu-font-family neovim nautilus conky wget feh \
xfce4-screenshooter xclip base-devel zsh zsh-completions acpi sysstat alsa-utils chromium firefox redshift python-pywal \
xorg xorg-xinit xorg-server xorg-server-devel xorg-xrandr xorg-xinput xbindkeys mesa dmenu compton i3-gaps

if [ $(pacman -Qe | grep 'intel-ucode\|amd-ucode' | wc -l) -eq 0 ]; then
    echo
    echo "Do you have an Intel CPU?"
    select yn in "Yes" "No"; do
        case $yn in
            Yes ) pacman -S intel-ucode; break;;
            No ) break;;
        esac
    done
fi

if [ $(pacman -Qe | grep 'intel-ucode\|amd-ucode' | wc -l) -eq 0 ]; then
    echo
    echo "Do you have an AMD CPU?"
    select yn in "Yes" "No"; do
        case $yn in
            Yes ) pacman -S amd-ucode; break;;
            No ) break;;
        esac
    done
fi

echo
echo "Installing AUR packages."
sudo -u $USERNAME yay -S yabar-git ttf-font-awesome-4 oh-my-zsh-git

echo
echo "Changing default shell to zsh."
sudo -u $USERNAME chsh -s /usr/bin/zsh

echo
echo "Installing pip packages."
pip install i3ipc
