#!/bin/bash

set -e

echo "Setting up user packages."
echo

BASIC_PACKAGES=( jdk14-openjdk openjdk14-doc openjdk14-src java-openjfx java-openjfx-doc java-openjfx-src openssh python python-pip r acpi sysstat mesa tlp )

MEDIA_PACKAGES=( pulseaudio pulseaudio-alsa pulseaudio-bluetooth pulseaudio-equalizer pulseaudio-jack pulseaudio-lirc pulseaudio-rtp pulseaudio-zeroconf pavucontrol alsa-card-profiles alsa-firmware alsa-lib alsa-oss  alsa-plugins alsa-topology-conf alsa-ucm-conf alsa-utils ffmpeg )

INTERFACE_PACKAGES=( i3-gaps compton dmenu ttf-dejavu ttf-font-awesome noto-fonts noto-fonts noto-fonts-cjk noto-fonts-extra noto-fonts-emoji xorg xorg-xinit xorg-server xorg-server-devel xorg-xrandr xorg-xinput xbindkeys xclip zsh zsh-completions python-pywal redshift xfce4-terminal xfce4-screenshooter ttf-ubuntu-font-family nautilus gvfs-mtp )

USEFUL_SOFTWARE=( gedit krita inkscape imagemagick vlc firefox chromium signal-desktop telegram-desktop discord pandoc pandoc-citeproc pandoc-crossref texlive-most texlive-lang biber rclone htop vnstat keepassxc tree shotwell feh wget cowsay lolcat sl nmap neovim asciiquarium audacity boost boost-libs tbb pigz clang rustup code opencv meson ninja graphviz stellarium tor torbrowser-launcher )

pacman -S base-devel "${BASIC_PACKAGES[@]}" "${MEDIA_PACKAGES[@]}" "${INTERFACE_PACKAGES[@]}" "${USEFUL_SOFTWARE[@]}"

systemctl enable tlp

if ! pacman -Qe | grep -q 'intel-ucode\|amd-ucode'; then
  echo
  echo "Do you have an Intel CPU?"
  select yn in "Yes" "No"; do
    case $yn in
      Yes ) pacman -S intel-ucode; break;;
      No ) 
        echo
        echo "Do you have an AMD CPU?"
        select yn in "Yes" "No"; do
          case $yn in
            Yes ) pacman -S amd-ucode; break;;
            No ) break;;
          esac
        done
        break;;
    esac
  done
fi

echo
echo "Installing AUR packages."
sudo -u "$USERNAME" yay -S yabar-git oh-my-zsh-git protonvpn-cli-ng

echo
echo "Changing default shell to zsh."
sudo -u "$USERNAME" chsh -s /usr/bin/zsh

echo
echo "Installing pip packages."
pip install i3ipc
