#!/bin/bash

set -e

echo "Setting up dotfiles."
echo

cd /home/"$USERNAME"
rm -rf .dotfiles

sudo -u "$USERNAME" git clone https://github.com/schutzekatze/.dotfiles
cd .dotfiles
sudo -u "$USERNAME" ./setup
