#!/bin/bash

set -e

echo "Setting up bootloader."
echo

bootloader_dev=$(df -h /boot | head -n 2 | tail -n 1 | awk '{print $1}')
os_dev=$(df -h / | head -n 2 | tail -n 1 | awk '{print $1}')

echo "Bootloader device at $bootloader_dev"
echo "OS device at $os_dev"
echo

echo "Installing bootloader."
bootctl --path=/boot install
echo

echo "Setting bootloader pacman hook."
mkdir -p /etc/pacman.d/hooks
echo "[Trigger]
Type = Package
Operation = Upgrade
Target = systemd

[Action]
Description = Updating systemd-boot
When = PostTransaction
Exec = /usr/bin/bootctl update" >/etc/pacman.d/hooks/systemd-boot.hook
echo "Hook file content:"
cat /etc/pacman.d/hooks/systemd-boot.hook
echo

echo "default arch" >/boot/loader/loader.conf

echo "title Arch Linux
linux /vmlinuz-linux" >/boot/loader/entries/arch.conf
if [ -f /boot/intel-ucode.img ]; then
    echo "initrd /intel-ucode.img" >>/boot/loader/entries/arch.conf
fi
if [ -f /boot/amd-ucode.img ]; then
    echo "initrd /amd-ucode.img" >>/boot/loader/entries/arch.conf
fi
echo "initrd /initramfs-linux.img
options root=$os_dev rw" >>/boot/loader/entries/arch.conf
echo "Arch conf file content:"
cat /boot/loader/entries/arch.conf

mkinitcpio -p linux
