#!/bin/bash

set -e

echo "Setting up bootloader."
echo

bootloader_root=$(df -h /boot | head -n 2 | tail -n 1 | awk '{print $1}')
os_root=$(df -h / | head -n 2 | tail -n 1 | awk '{print $1}')
os_dev=$(cryptsetup status cryptroot | grep device | awk '{ print $2 }')
os_dev_uuid=$(blkid | grep "$os_dev" | awk '{ print $2 }' | awk -F'=' '{ print $2 }' | awk -F'"' '{ print $2 }')

echo "Bootloader at $bootloader_root"
echo "OS at $os_root"
echo

echo "Installing bootloader."
bootctl --path=/boot install
echo

echo "Setting bootloader pacman hook."
mkdir -p /etc/pacman.d/hooks
echo "[Trigger]
Type = Package
Operation = Upgrade
Target = systemd

[Action]
Description = Updating systemd-boot
When = PostTransaction
Exec = /usr/bin/bootctl update" >/etc/pacman.d/hooks/systemd-boot.hook
echo "Hook file content:"
cat /etc/pacman.d/hooks/systemd-boot.hook
echo

echo "default archlinux" >/boot/loader/loader.conf
entry=/boot/loader/entries/archlinux.conf

echo "title Arch Linux
linux /vmlinuz-linux" >"$entry"
if [ -f /boot/intel-ucode.img ]; then
    echo "initrd /intel-ucode.img" >>"$entry"
fi
if [ -f /boot/amd-ucode.img ]; then
    echo "initrd /amd-ucode.img" >>"$entry"
fi
echo "initrd /initramfs-linux.img
options cryptdevice=UUID=$os_dev_uuid:cryptroot root=$os_root rw lsm=lockdown,yama,apparmor,bpf" >>"$entry"

echo "Arch conf file content:"
cat "$entry"
