#!/bin/bash

set -e

echo "Adjusting initcpio"
echo

new_hooks=$(sed 's~^HOOKS=(.*)$~HOOKS=(base udev autodetect keyboard modconf block ykfde encrypt filesystems fsck)~' /etc/mkinitcpio.conf)
echo "$new_hooks" >/etc/mkinitcpio.conf

mkinitcpio -P
