#!/bin/bash

set -e

echo "Setting up VPN"
echo

function enable_vpn() {
    protonvpn init

    echo "[Unit]
Description=Turn on VPN once online
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root
ExecStart=/home/$USERNAME/.utils/connect-vpn
ExecStop=/home/$USERNAME/.utils/disconnect-vpn
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target" >/etc/systemd/system/vpn.service

    systemctl enable vpn.service

    echo "VPN enabled."
}

function disable_vpn() {
    systemctl disable vpn.service 2>/dev/null
    rm -f /etc/systemd/system/vpn.service
}

disable_vpn
echo "Do you want to enable VPN?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) enable_vpn; break;;
        No ) break;;
    esac
done
