#!/bin/bash

set -e

echo "Setting up VPN"
echo

function enable_vpn() {
  PREV_SUDO_USER="$SUDO_USER"
  PREV_SUDO_UID="$SUDO_UID"
  PREV_SUDO_GID="$SUDO_GID"
  PREV_PWD=$(pwd)
  
  export SUDO_USER="$USERNAME"
  SUDO_UID=$(sudo -u "$USERNAME" id -u)
  SUDO_GID=$(sudo -u "$USERNAME" id -g)
  export SUDO_UID
  export SUDO_GID
  cd /home/"$USERNAME"
  protonvpn init
 
  cd "$PREV_PWD"
  export SUDO_USER="$PREV_SUDO_USER"
  export SUDO_UID="$PREV_SUDO_UID"
  export SUDO_GID="$PREV_SUDO_GID"

  echo "[Unit]
Description=Turn on VPN once online
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root
ExecStart=/home/$USERNAME/.utils/connect-vpn %i
ExecStop=/home/$USERNAME/.utils/disconnect-vpn
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target" >/etc/systemd/system/vpn@.service

  systemctl enable vpn@fast.service

  echo "VPN enabled."
}

function disable_vpn() {
  systemctl disable vpn@fast.service 2>/dev/null
  rm -f /etc/systemd/system/vpn@.service
}

disable_vpn
echo "Do you want to enable VPN?"
select yn in "Yes" "No"; do
  case $yn in
    Yes ) enable_vpn; break;;
    No ) break;;
  esac
done
